// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ9U9BYgIc7o8CjqUnUbATv6_1o0vVV-0',
    appId: '1:1021116413046:web:6b05dc18fb18992d1b1b57',
    messagingSenderId: '1021116413046',
    projectId: 'ai-generations-app',
    authDomain: 'ai-generations-app.firebaseapp.com',
    storageBucket: 'ai-generations-app.appspot.com',
    measurementId: 'G-8CYG0ZX781',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6cUaDwUXJ4_FBykD1bpifSlUSqRhrbsc',
    appId: '1:1021116413046:android:4548b18dd74c412e1b1b57',
    messagingSenderId: '1021116413046',
    projectId: 'ai-generations-app',
    storageBucket: 'ai-generations-app.appspot.com',
  );
}
